# Generated by Django 3.2.16 on 2024-05-10 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emailcode',
            old_name='verification_code',
            new_name='code',
        ),
    ]
