version: '3.3'

volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    image: toomike/my_shop_backend
    env_file: .env
    depends_on:
      - db
    volumes:
      - static:/backend_static
      - media:/app/media

  nginx:
    image: toomike/my_shop_nginx
    depends_on:
      - backend
    ports:
      - "8000:80"
    volumes:
      - media:/media
      - static:/backend_static
