# Generated by Django 3.2.16 on 2024-05-31 10:50

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название категории')),
                ('description', models.TextField(max_length=450, verbose_name='Описание категории')),
                ('slug', models.SlugField(unique=True, verbose_name='Идентификатор')),
                ('is_active', models.BooleanField(default=True, verbose_name='Опубликовано')),
            ],
            options={
                'verbose_name': 'категория',
                'verbose_name_plural': 'Категории',
                'default_related_name': 'category',
            },
        ),
        migrations.CreateModel(
            name='Colour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Название цвета')),
            ],
            options={
                'verbose_name': 'цвет',
                'verbose_name_plural': 'Цвета',
            },
        ),
        migrations.CreateModel(
            name='ColourProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'цвет товара',
                'verbose_name_plural': 'Цвета товара',
                'default_related_name': 'colourproduct',
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название страны')),
            ],
            options={
                'verbose_name': 'страна',
                'verbose_name_plural': 'Страны',
                'default_related_name': 'country',
            },
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название производителя')),
                ('slug', models.SlugField(unique=True, verbose_name='Идентификатор')),
                ('is_active', models.BooleanField(default=True, verbose_name='Опубликовано')),
            ],
            options={
                'verbose_name': 'производитель',
                'verbose_name_plural': 'Производители',
                'default_related_name': 'manufacturer',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название товара')),
                ('description', models.TextField(max_length=400, verbose_name='Описание товара')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('sale', models.IntegerField(blank=True, null=True, verbose_name='Скидка')),
                ('actual_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Цена со скидкой')),
                ('is_active', models.BooleanField(default=True, verbose_name='Опубликовано')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Время добавления')),
                ('image', models.ImageField(blank=True, upload_to='product_images', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'товар',
                'verbose_name_plural': 'Товары',
                'ordering': ('created',),
                'default_related_name': 'product',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=1000, verbose_name='Текст отзыва')),
                ('photo', models.FileField(blank=True, null=True, upload_to='photo', verbose_name='Фото')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('rating', models.PositiveSmallIntegerField(choices=[(5, '5 - Отлично'), (4, '4 - Очень хорошо'), (3, '3 - Хорошо'), (2, '2 - Плохо'), (1, '1 - Очень плохо')], verbose_name='Рейтинг')),
            ],
            options={
                'verbose_name': 'отзыв',
                'verbose_name_plural': 'Отзывы',
                'ordering': ('-created_at',),
                'default_related_name': 'reviews',
            },
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название магазина')),
                ('adress', models.TextField(max_length=300, verbose_name='Адрес магазина')),
            ],
            options={
                'verbose_name': 'магазин',
                'verbose_name_plural': 'Магазины',
                'default_related_name': 'shop',
            },
        ),
        migrations.CreateModel(
            name='ShopProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shopproduct', to='main.product', verbose_name='Товар')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shopproduct', to='main.shop', verbose_name='Магазин')),
            ],
            options={
                'default_related_name': 'shopproduct',
            },
        ),
        migrations.CreateModel(
            name='ShopProductColourProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='Количество')),
                ('colourproduct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shopproductcolourproduct', to='main.colourproduct', verbose_name='Цвета товара')),
                ('shopproduct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shopproductcolourproduct', to='main.shopproduct', verbose_name='Товар в магазине')),
            ],
            options={
                'default_related_name': 'shopproductcolourproduct',
            },
        ),
        migrations.CreateModel(
            name='SerialNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=50, verbose_name='Серийный номер')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'серийный номер',
                'verbose_name_plural': 'Серийные номера',
            },
        ),
    ]
