# Generated by Django 3.2.16 on 2024-04-21 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название категории')),
                ('description', models.TextField(max_length=450, verbose_name='Описание категории')),
                ('slug', models.SlugField(unique=True, verbose_name='Идентификатор')),
                ('is_active', models.BooleanField(default=True, verbose_name='Опубликовано')),
            ],
            options={
                'verbose_name': 'категория',
                'verbose_name_plural': 'Категории',
                'default_related_name': 'category',
            },
        ),
        migrations.CreateModel(
            name='Colour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Название цвета')),
            ],
            options={
                'verbose_name': 'цвет',
                'verbose_name_plural': 'Цвета',
            },
        ),
        migrations.CreateModel(
            name='ColourSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('colours', models.ManyToManyField(related_name='colourset', to='main.Colour', verbose_name='цвет')),
            ],
            options={
                'verbose_name': 'цвет товара',
                'verbose_name_plural': 'Цвета товара',
                'default_related_name': 'colourset',
            },
        ),
        migrations.CreateModel(
            name='ColourSetProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('colourset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.colourset', verbose_name='Цвета')),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название страны')),
            ],
            options={
                'verbose_name': 'страна',
                'verbose_name_plural': 'Страны',
                'default_related_name': 'country',
            },
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название производителя')),
                ('slug', models.SlugField(unique=True, verbose_name='Идентификатор')),
                ('is_active', models.BooleanField(default=True, verbose_name='Опубликовано')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manufacturer', to='main.country', verbose_name='Страна производителя')),
            ],
            options={
                'verbose_name': 'производитель',
                'verbose_name_plural': 'Производители',
                'default_related_name': 'manufacturer',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название товара')),
                ('description', models.TextField(max_length=400, verbose_name='Описание товара')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('sale', models.IntegerField(blank=True, null=True, verbose_name='Скидка')),
                ('rating', models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='Рейтинг')),
                ('is_active', models.BooleanField(default=True, verbose_name='Опубликовано')),
                ('image', models.ImageField(blank=True, upload_to='product_images', verbose_name='Изображение')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='main.category', verbose_name='Категрия')),
                ('colourset', models.ManyToManyField(related_name='product', through='main.ColourSetProduct', to='main.ColourSet', verbose_name='Цвета товара')),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='main.manufacturer', verbose_name='Производитель')),
            ],
            options={
                'verbose_name': 'товар',
                'verbose_name_plural': 'Товары',
                'default_related_name': 'product',
            },
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название магазина')),
                ('adress', models.TextField(max_length=300, verbose_name='Адрес магазина')),
            ],
            options={
                'verbose_name': 'магазин',
                'verbose_name_plural': 'Магазины',
                'default_related_name': 'shop',
            },
        ),
        migrations.CreateModel(
            name='ShopProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.product', verbose_name='Товар')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.shop', verbose_name='Магазин')),
            ],
        ),
        migrations.CreateModel(
            name='ShopProductColourSetProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='Количество')),
                ('coloursetproduct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.coloursetproduct', verbose_name='Цвета товара')),
                ('shopproduct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.shopproduct', verbose_name='Товар в магазине')),
            ],
        ),
        migrations.CreateModel(
            name='SerialNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=50, verbose_name='Серийный номер')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'серийный номер',
                'verbose_name_plural': 'Серийные номера',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='shop',
            field=models.ManyToManyField(blank=True, related_name='product', through='main.ShopProduct', to='main.Shop', verbose_name='Магазин'),
        ),
        migrations.AddField(
            model_name='coloursetproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.product', verbose_name='Товар'),
        ),
    ]
