# Generated by Django 3.2.16 on 2024-04-24 16:30

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coloursetproduct',
            options={'verbose_name': 'цвет товара', 'verbose_name_plural': 'Цвета товара'},
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=1000, verbose_name='Текст отзыва')),
                ('photo', models.FileField(blank=True, upload_to='photo', verbose_name='Фото')),
                ('creted_at', models.DateTimeField(auto_now_add=True)),
                ('rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(limit_value=5, message='Оценка не может быть больше 10 баллов'), django.core.validators.MinValueValidator(limit_value=1, message='Оценка не может быть меньше 1го балла')], verbose_name='Рейтинг')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='main.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'отзыв',
                'verbose_name_plural': 'Отзывы',
                'ordering': ('-creted_at',),
                'default_related_name': 'reviews',
            },
        ),
    ]
