# Generated by Django 3.2.16 on 2024-04-25 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_review_author'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'default_related_name': 'reviews', 'ordering': ('-created_at',), 'verbose_name': 'отзыв', 'verbose_name_plural': 'Отзывы'},
        ),
        migrations.RenameField(
            model_name='review',
            old_name='creted_at',
            new_name='created_at',
        ),
    ]
