# Generated by Django 3.2.16 on 2024-04-25 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20240425_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.PositiveSmallIntegerField(choices=[(5, '5 - Отлично'), (4, '4 - Очень хорошо'), (3, '3 - Хорошо'), (2, '2 - Плохо'), (1, '1 - Очень плохо')], verbose_name='Рейтинг'),
        ),
    ]
