# Generated by Django 3.2.16 on 2024-04-26 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_review_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='rating',
        ),
    ]
