# Generated by Django 3.2.16 on 2024-05-11 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20240510_1405'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='colourproduct',
            options={'default_related_name': 'colourproduct', 'verbose_name': 'цвет товара', 'verbose_name_plural': 'Цвета товара'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'default_related_name': 'product', 'ordering': ('created',), 'verbose_name': 'товар', 'verbose_name_plural': 'Товары'},
        ),
        migrations.AlterModelOptions(
            name='shopproduct',
            options={'default_related_name': 'shopproduct'},
        ),
        migrations.AlterModelOptions(
            name='shopproductcolourproduct',
            options={'default_related_name': 'shopproductcolourproduct'},
        ),
        migrations.AlterField(
            model_name='colourproduct',
            name='colour',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colourproduct', to='main.colour', verbose_name='Цвета'),
        ),
        migrations.AlterField(
            model_name='colourproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colourproduct', to='main.product', verbose_name='Товар'),
        ),
        migrations.AlterField(
            model_name='shopproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shopproduct', to='main.product', verbose_name='Товар'),
        ),
        migrations.AlterField(
            model_name='shopproduct',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shopproduct', to='main.shop', verbose_name='Магазин'),
        ),
        migrations.AlterField(
            model_name='shopproductcolourproduct',
            name='colourproduct',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shopproductcolourproduct', to='main.colourproduct', verbose_name='Цвета товара'),
        ),
        migrations.AlterField(
            model_name='shopproductcolourproduct',
            name='shopproduct',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shopproductcolourproduct', to='main.shopproduct', verbose_name='Товар в магазине'),
        ),
    ]
