# Generated by Django 3.2.16 on 2024-05-12 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20240511_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to='photo', verbose_name='Фото'),
        ),
    ]
